### ISSUE TITLE
Wrap this stuff! 

### ISSUE THREAD

**Issue by soggybag** [nsafai/nsafai.github.io#2]
https://github.com/nsafai/nsafai.github.io/blob/040f0722d064eaf8c9214bea3258e76650073e9b/index.html#L11

I feel like best practice is to put all your content in a container div. It will make it easier to work with the layout. As is you'll need to apply layout to the body tag which is not good practice and asking for trouble in the future. 

If you are expecting changes to come from your team you'll want to have a wrapper around your content for flexibility.

**Comment by nsafai** [comment]
understood! will do
